POST http://localhost:7071/api/customers
X-TenantId: awesomeinc

{
    "type":"Person",
    "id":"8001015144588",
    "email":"dddddddd"
}

###
http://localhost:7071/api/customers/3a5f3ca1-b903-463a-ad4d-f743288f51d1
X-TenantId: awesomeinc